### ISSUE TITLE
Unhandled error: ENOTFOUND stunserver.org

### ISSUE THREAD

**Issue by amingilani** [blinktrade/BlinkTradeJS#1]
A script that was working perfectly before just started throwing errors.

```
$ node index.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND stunserver.org
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

The `index.js` file only contains the following lines:

```javascript
// Setup BlinkTrade
var BlinkTrade = require('blinktrade');
var BlinkTradeWS = BlinkTrade.BlinkTradeWS;
var blinktrade = new BlinkTradeWS({
    prod: true
});
```

**Comment by amingilani** [comment]
Found the line that contains the server:

https://github.com/blinktrade/BlinkTradeJS/blob/master/src/util/stun.js#L64

**Comment by amingilani** [comment]
It seems that stunserver.org is down, or deprecated.
![screen shot 2016-11-16 at 5 12 11 pm](https://cloud.githubusercontent.com/assets/1188552/20346794/fcc54012-ac1f-11e6-850b-48cfc05f469a.png)

**Comment by amingilani** [comment]
It appears to be an issue with my dns.

![screen shot 2016-11-16 at 5 12 22 pm](https://cloud.githubusercontent.com/assets/1188552/20346806/0f22cd06-ac20-11e6-9e1a-d80313bee7ea.png)

Investigating.

**Comment by amingilani** [comment]
[pingdom doesn't report any critical errors](http://dnscheck.pingdom.com/?domain=stunserver.org&timestamp=1479298490&view=1) probably just my dns.

**Comment by amingilani** [comment]
Not much we can do at this point, i'll just have to live with this anomaly until it goes away.

```bash
$ ping stunserver.org
ping: cannot resolve stunserver.org: Unknown host
```

**Comment by cesardeazevedo** [comment]
Hi @amingilani, thank you for the feedback, i'll take a look at it...

@pinhopro should we ignore a "unreachabled" stun server?

I think i'll reopen this.
