### ISSUE TITLE
Wrong fiat balance

### ISSUE THREAD

**Issue by zavan** [blinktrade/BlinkTradeJS#10]
The REST API seem to be returning the wrong fiat balance.
Currently I have 0 BRL and 0 BTC at FoxBit (4), but when asking the REST API for my balance:
```javascript
let BlinkTradeRest = require('blinktrade').BlinkTradeRest;

let rest = new BlinkTradeRest({
  prod: true,
  key: 'mykey',
  secret: 'mysecret',
  currency: 'BRL',
  brokerId: 4
});

rest.balance().then(function(balance) {
  console.log(balance);
});
```
I get this:
```javascript
{ '4': { BTC_locked: 0, BRL: 233915, BTC: 0, BRL_locked: 0 },
  MsgType: 'U3',
  ClientID: 123456,
  BalanceReqID: 123456,
  Available: { BRL: 233915, BTC: 0 } }
```
233915 BRL! Am I richer than I thought?! :stuck_out_tongue:

**Comment by elias19r** [comment]
My guess: BlinkTrade uses 8 decimal precision for all currencies. So you actually have 233915 / 1e8 = 0.00233915 BRL which rounded to 2 decimal places will result in 0.00 BRL.

Waiting for a developer to confirm.

**Comment by zavan** [comment]
@elias19r You're probably correct. Waiting for confirmation too, but thanks!

**Comment by cesardeazevedo** [comment]
Yes, @elias19r is right, the balance value is on the 8 decimal precision, `R$ 0.00233915` is your actual balance, but on our interface is rounded to `R$ 0.00`.
