### ISSUE TITLE
How to know rejection reasons?

### ISSUE THREAD

**Issue by uliporeggia** [blinktrade/BlinkTradeJS#17]
Hello again!
I am still testing things and another problem comes out: there is no documentation about rejection reasons. I am trying to `blinktrade.sendOrder()` with no success.
This is the returned message:

```
{ 
  OrderID: null,
  Volume: 0,
  ExecID: null,
  ExecType: '8',
  OrdStatus: '8',
  LeavesQty: 0,
  Price: 371930000000,
  OrderQty: 369265,
  LastShares: 0,
  LastPx: 0,
  CxlQty: 0,
  TimeInForce: '1',
  CumQty: 0,
  MsgType: '8',
  ClOrdID: 9667187,
  OrdType: '2',
  OrdRejReason: '3',
  Side: '1',
  Symbol: 'BTCBRL',
  ExecSide: '1',
  AvgPx: 0
}
```

How to know what `OrdRejReason: '3'` means?

**Comment by cesardeazevedo** [comment]
Hi, those terms comes from fix protocol, `OrdRejReason: '3'` is for "Order exceeds limit", which means that you don't have enough balance or you may have open orders.

You access all reasons directly on the fix documentation, but we don't implemented all reasons though.
http://www.onixs.biz/fix-dictionary/4.2/tagNum_103.html

I will update our documentation to add these missing "fix" details.

**Comment by uliporeggia** [comment]
Very nice to know about this protocol! Yes, this really is an important information to put in documentation.
Thanks again.

**Comment by uliporeggia** [comment]
Well, still something wrong:

```
{ '4': { BTC_locked: 0, BRL: 687904, BTC: 738529, BRL_locked: 0 },
  MsgType: 'U3',
  ClientID: 90803947,
  BalanceReqID: 4785873,
  Available: { BRL: 687904, BTC: 738529 } }
```
```
{ OrderID: null,
  Volume: 0,
  ExecID: null,
  ExecType: '8',
  OrdStatus: '8',
  LeavesQty: 0,
  Price: 372001000000,
  OrderQty: 123,
  LastShares: 0,
  LastPx: 0,
  CxlQty: 0,
  TimeInForce: '1',
  CumQty: 0,
  MsgType: '8',
  ClOrdID: 1001994,
  OrdType: '2',
  OrdRejReason: '3',
  Side: '2',
  Symbol: 'BTCBRL',
  ExecSide: '2',
  AvgPx: 0 }
```

Trying to sell 0,00000123 for 3720,01 right? Why rejection reason is 3 if I have 0,00738529 available?

**Comment by cesardeazevedo** [comment]
`0,00000123` is indeed too small, and exceeds the minimum limit of 0.0001 to send orders (although this isn't part of fix protocol), it's just our measure to avoid "dust orders".

I will add these details on our documentation soon.

**Comment by uliporeggia** [comment]
Right, that was the problem!

**Comment by cesardeazevedo** [comment]
Added on docs. https://github.com/blinktrade/docs/commit/37434c7bb59acfb4f94eca66947ace88fc85fd8c

Let me know if you have any other issues.
