### ISSUE TITLE
Clarification Orders vs Instant Trades

### ISSUE THREAD

**Issue by amingilani** [blinktrade/BlinkTradeJS#2]
Hello

I need to make instant trades on Urdubit, and while your documentation talks about [sending and cancelling orders](https://github.com/blinktrade/BlinkTradeJS#send-and-cancelling-orders), there's no mention of instant trades.

Is this an available API endpoint? How do I use it?

**Comment by amingilani** [comment]
Monitoring Websocket Requests.

Just bought bitcoin:
Sold 0.00124698 BTC for 98 PKR
```
{
    "MsgType": "D",
    "ClOrdID": "2386667",
    "Symbol": "BTCPKR",
    "Side": "2",
    "OrdType": "2",
    "Price": 7854400000000,
    "OrderQty": 124698,
    "ClientID": 90878789,
    "FingerPrint": 703338308,
    "STUNTIP": {
        "local": "192.168.1.16",
        "public": []
    }
}
```

Just sold bitcoin:
Bought 0.00121262 BTC for 98 PKR out of which, I believe 1 PKR went to fees
```
{
    "MsgType": "D",
    "ClOrdID": "3962101",
    "Symbol": "BTCPKR",
    "Side": "1",
    "OrdType": "2",
    "Price": 7999200000000,
    "OrderQty": 121262,
    "ClientID": 90878789,
    "FingerPrint": 703338308,
    "STUNTIP": {
        "local": "192.168.1.16",
        "public": []
    }
}
```

**Comment by amingilani** [comment]
Please don't tell me I need to subscribe to the orderbook, calculate the instant trade value and then open an order at that price 😮

**Comment by amingilani** [comment]
How do fees tie into this?

**Comment by cesardeazevedo** [comment]
I think you're talking about `market` order right? unfortunately we just provide `limited` orders, which you need specify a price, but the main point is, market orders can be very dangerous in a low liquidity markets, i would never rely in automate a market order, it really depends on the market and the liquidity.

I think the best and recommended way you can do without subscribe to the orderbook, is subscribing to ticker and get `BestBid` and `BestAsk`, and send order at the best price and apply a margin as you wish.

Regarding the fees, i don't really got it what's going on, if you need a better visualization on the trade fees, you should take a look at the ledger directly on the urdubit exchange...

Tell me if you got it.

**Comment by amingilani** [comment]
I understand the risks but unfortunately I really am looking for market
orders.

Do you have a best price trading policy on your engine? If I open a limit
order for 1 BTC at 1 million will it fill it using the lowest price first?

**Comment by pinhopro** [comment]
A market order is nothing more than a limited order with very low price in case you are selling, or very high price in case you are buying

the price is always determined by the execution price.

**Comment by amingilani** [comment]
@pinhopro thanks! That answers my question! :D
