### ISSUE TITLE
Trades method with trade id query

### ISSUE THREAD

**Issue by cryptoqween** [blinktrade/BlinkTradeJS#20]
Hello, 

I was doing a query using timestamp, but since the API returns 100 trades at a time, there will be cases when more than 100 trades will have the same timestamps so some will be missing from the query.

Example:
https://api.blinktrade.com/api/v1/VEF/trades?since=1415795682

Can you make query with tradeID possible? TradeId-s are unique so this problem would not occur.

Thanks!

**Comment by cesardeazevedo** [comment]
Hi, i am not sure if i understood it properly, but i don't think that is possible, the rest endpoint is quite limited, the best way to fetch more than 100 trades would be by fetching several pages on tradeHistory through our WebSocket api.

```js
var BlinkTradeWS = require('blinktrade').BlinkTradeWS;

var blinktrade = new BlinkTradeWS();

blinktrade.connect().then(function() {
  return blinktrade.tradeHistory({ page: 0, since: '1415795682' });
}).then(function(trades) {
  console.log(trades);
})

```

**Comment by cryptoqween** [comment]
Hi, thanks for the quick reply. 
Alright, I try this, which parameter can I use to choose the exchange i want the data from?

**Comment by cesardeazevedo** [comment]
You usually do that on the BlinkTradeWS constructor `new BlinkTrade({ brokerId: 5 })`, but on the `tradeHistory` there's no such filter, and just return the trades from all symbols, i heard that this filter was to be implemented, but i am not sure of it.

**Comment by cryptoqween** [comment]
Hi there, thanks.

Can you double check the response? Currently running your code returns an empty object for 'TradeHistoryGrp'.

**Comment by cesardeazevedo** [comment]
Yes, it's correct, it's because it's using testnet by default, and currently there's no trades on testnet, if you need production data, you need pass the `prod: true` on the constructor as follows `new BlinkTradeWS({ prod: true })`, authentication is no needed to fetching trades.

**Comment by cryptoqween** [comment]
Hi thanks, i set prod to true, and got the following error:
Error: unexpected server response (521)
type: 'error',
