### ISSUE TITLE
WebSocket API not working

### ISSUE THREAD

**Issue by hasanaliqureshi** [blinktrade/BlinkTradeJS#22]
I am trying generate new btc deposit address but its giving me error. 
What I am doing wrong ?
Thanks

![bl](https://user-images.githubusercontent.com/12941929/31250716-2af48cd6-aa35-11e7-9a94-f627b3a4d549.png)
![bl1](https://user-images.githubusercontent.com/12941929/31250717-2af90bee-aa35-11e7-9d99-ab262b64b0ff.png)

**Comment by gilbertovb** [comment]
I have the same issue.
The host api.testnet.blinktrade.com doesn't work:
[Error: getaddrinfo ENOTFOUND api.testnet.blinktrade.com api.testnet.blinktrade.com:443]
And the prod I got the error: 
`{ Username: '',
  NeedSecondFactor: false,
  UserStatusText: 'MSG_LOGIN_ERROR_INVALID_USERNAME_OR_PASSWORD',
  SecondFactorType: null,
  UserReqID: 7946650,
  UserStatus: 3,
  MsgType: 'BF' }`

My code is:
`var BlinkTradeWS = require('blinktrade').BlinkTradeWS;
var blinktrade = new BlinkTradeWS({ prod: true });
blinktrade.connect().then(function() {
  return blinktrade.login({ username: 'user', password: 'pass' });
}).then(function(logged) {
  console.log(logged);
}).catch(function(err) {
  console.log(err);
});`

What is your problem?

**Comment by cesardeazevedo** [comment]
Sorry for the delay guys, but i think both of you are forgetting to pass the brokerId param? the default is 5 which is the brokerId for testnet, so `{ prod: true, brokerId: 5 }` doesn't make much sense in this case since brokerId only works with `{ prod: false }`.

**Comment by gilbertovb** [comment]
Now, it worked, but I have to use the API key as username and API secret as password.

Thank you.

**Comment by cesardeazevedo** [comment]
Yeah, without an API key would asked your for second factor authentication, on email or google auth, but with an API key this isn't needed

**Comment by hasanaliqureshi** [comment]
It worked. Thanks

**Comment by affankhan43** [comment]
I'm trying to connect websocket but it gives me error
what i'm doing wrong

![image](https://user-images.githubusercontent.com/25964796/33602259-92f91886-d9d0-11e7-8e9f-0c2f4c13e246.png)

![11](https://user-images.githubusercontent.com/25964796/33602356-e03ed34c-d9d0-11e7-8d5d-789a4eb47958.png)
)

**Comment by gilbertovb** [comment]
Try to use " 
Below is my code:
`var BlinkTradeWS = require("blinktrade").BlinkTradeWS;
var blinktrade = new BlinkTradeWS({ prod: true, brokerId: 4 });
blinktrade.connect().then(function() {
        return blinktrade.login({ "username": "******************************", "password": "********************" });
}).then(function(logged) {
        console.log(logged);
}).catch(function(err) {
        console.log(err);
});`

**Comment by affankhan43** [comment]
i tried this code but still same error

**Comment by orapouso** [comment]
I'm also getting this error but only if I use blinktrade sdk in the browser. From both Firefox or Chrome. 
```
var BlinkTradeWS = require("blinktrade").BlinkTradeWS
var blinktrade = new BlinkTradeWS({ prod: true, brokerId: 4 })

blinktrade.connect()
```

Chrome gives the error: "Error during WebSocket handshake: Unexpected response code: 403". It seems that it is expecting some kind of authentication prior to connection, but that is weird.

**Comment by orapouso** [comment]
After doing some research I found that may be this is a cross origin issue. The server at `wss://ws.blinktrade.com/trade/` would need to allow all origins ("*") to connect, otherwise the browser blocks the connection from happening.

**Comment by cesardeazevedo** [comment]
I'm really sorry for not point it out on our documentation before, this has been a issue for us for a long time, but yes, it's a cross origin issue, and we can't allow it right now due security reasons.

Since we have a full feature API, we just can't expose features such as signup, change password for everyone, there's a lot concerns from @pinhopro about it, but we are planning to provide a public (but limited) WebSocket endpoint in a near future.

Everything will work on the server side though, without any restriction, but we know that this isn't might be convenient for everyone who just wants to run on the browser, so we apologize for this situation.

I hope you guys can understand this issue and our concerns, and i really hope this can change in the future.

Regards.
