### ISSUE TITLE
 Cannot find name 'Ledger'. When using on Typescript.

### ISSUE THREAD

**Issue by Judahh** [blinktrade/BlinkTradeJS#29]
I got this error: "node_modules/blinktrade/index.d.ts(282,32): error TS2304: Cannot find name 'Ledger'."  when I run TSC.

**Comment by cesardeazevedo** [comment]
Sorry, i didn't take a look at typescript recently, i'm going to fix it.

**Comment by cesardeazevedo** [comment]
Fixed at c8ee6f50b35ce0d5d99566fc9d5170e88f08e589 and published at `0.0.13`
