### ISSUE TITLE
Calls to MyOrders are not returning the correct information

### ISSUE THREAD

**Issue by felipegtx** [blinktrade/BlinkTradeJS#30]
Hi, it looks like that the call to `blinktrade.myOrders()` doesn't actually return the list of open orders and, worst of all, doesn't follow the expected response format [described here](https://blinktrade.com/docs/#my-orders), as you can see in the screenshots bellow.

![image](https://user-images.githubusercontent.com/1022404/34070287-90835026-e24a-11e7-99f8-bd7d2dc027e4.png)

![image](https://user-images.githubusercontent.com/1022404/34070274-69b5dcac-e24a-11e7-8d56-3281de9d6e46.png)

![image](https://user-images.githubusercontent.com/1022404/34070315-44949962-e24b-11e7-86f2-1021fbedac1e.png)

**Comment by cesardeazevedo** [comment]
That's weird, are you using rest or websockets?

**Comment by felipegtx** [comment]
It's REST, the code looks like the follow:

```
blinktrade.myOrders().then(function(ordersRes) {
 console.log(ordersRes)
});
```

**Comment by cesardeazevedo** [comment]
Are you using production environment or testnet?, i am getting very weird behavior on our testnet with rest, but in production is working fine.

Are your construction correct?

```js
var blinktrade = new BlinkTradeRest({
  key: 'KEY',
  secret: 'SECRET',
  brokerId: 4, // FOXBIT
  prod: true, // production
})

blinktrade.myOrders().then(function(data) {
  console.log(data)
})

```

**Comment by felipegtx** [comment]
yeah, I have exactly the same code. The only extra thing I have is the currency set to `BRL`.

**Comment by felipegtx** [comment]
PS: I've tried hooking into the execution report and it's working fine. I'll go ahead and use that approach instead.

**Comment by cesardeazevedo** [comment]
A question, did you make sure that you checked the "Order History" checkbox permission when creating the API Key?

The execution report is the right way to get your orders that you just sent in the current session, since you have realtime updates when your orders was executed, and the myOrders is more like for history reference.

**Comment by felipegtx** [comment]
Yeah, I tough of that but, also for some reason that I don't understand, The subscription to the order book doesn't update. Here's what I have so far:

```javascript
blinktradeWs.connect().then(function() {
    
    return blinktradeWs.login({ username: security.user, password: security.password });

}).then(function(logged) {
    
    blinktradeWs.executionReport()
        .on('EXECUTION_REPORT:NEW', onNew)
        .on('EXECUTION_REPORT:PARTIAL', onPartial)
        .on('EXECUTION_REPORT:EXECUTION', onExecution)
        .on('EXECUTION_REPORT:CANCELED', onCanceled)
        .on('EXECUTION_REPORT:REJECTED', onRejected);
  
    blinktradeWs.subscribeOrderbook(['BTCBRL']).then(handleBook);
});
```

The `handleBook` delegate is only being called once.

**Comment by cesardeazevedo** [comment]
Execution report only report changes of your orders, if you want to listen all orderbook changes you should implement in this way.

https://github.com/blinktrade/BlinkTradeJS/blob/master/examples/eventEmitters.js#L65-L70

**Comment by felipegtx** [comment]
Nice! I was referring to the `subscribeOrderbook` section. I didn't know you guys have ids on that one too. Thanks!

**Comment by felipegtx** [comment]
I'd suggest getting rid of the sample file `.\examples\orderBookWebSocket.js` since that example might get other people confused about the usage of this particular infrastructure.

**Comment by cesardeazevedo** [comment]
The `.then(handleBook)` will only be called once , because it's a promise and you can't resolve a promise twice, that's why we provide event emitters.

And yes indeed, some examples are confusing, i will try to get some time to improve them, thanks for the feedback.

**Comment by felipegtx** [comment]
I guess this will be my last question on this topic. What's the difference between the following events?

```javascript
  .on('EXECUTION_REPORT:PARTIAL', onExecutionReportPartial)
  .on('EXECUTION_REPORT:EXECUTION', onExecutionReportExecution)
```

Meaning, will a partially executed order also triggers the `onExecutionReportExecution` delegate?

**Comment by cesardeazevedo** [comment]
`EXECUTION_REPORT:PARTIAL ` won't trigger `onExecutionReportExecution`, the `EXECUTION_REPORT:EXECUTION` will only be called when your order is fully executed.

**Comment by felipegtx** [comment]
Ok, so lets say I place an order on `1 BTC` for `BRL 100`.

If that order gets partially executed with `0.7 BTC`, then fulfilled the remaining `0.3` on a second execution.

Would I receive two **independent** reports? 

One with `OrderQty` relative to the `0.7BTC` on the `PARTIAL` delegate and another with `OrderQty` of `0.3BTC` on the `EXECUTION`?

**Comment by cesardeazevedo** [comment]
Yes, that's correct, you can try yourself on the testnet https://testnet.blinktrade.com logging as `rodrigo`/`abc12345` (and create another account to test and add some funds to test), and run the [eventEmitter.js](https://github.com/blinktrade/BlinkTradeJS/blob/master/examples/eventEmitters.js) because i will pretty much do the same to tell you 😅

**Comment by felipegtx** [comment]
One other thing that I noticed is that, from time to time, when running the app the notifications just stop coming from the Order Book. Is there a method that I can use to try and find disconections and errors from that infrastructure - so I can try to restart the subscription.

**Comment by cesardeazevedo** [comment]
You should send heartbeat requests each 20 seconds in order to keep the websocket connected.
I think there's no method to handle disconnections right now, but it's something that could be implemented.

**Comment by felipegtx** [comment]
I though that the heartbeat signal was already embedded in the subscriber's code. What's the method I need to call in order to make that call?

**Comment by cesardeazevedo** [comment]
It's not, just `blinktrade.heartbeat()` as it shows in our [documentation](https://blinktrade.com/docs/#connectivity)

**Comment by felipegtx** [comment]
Is there a way to ask for all the executed orders I've placed? 

Also, is there a way to find out what was payed to the exchange for each individual order executed?

**Comment by cesardeazevedo** [comment]
I just publish at `0.0.15` a filter property on [myOrders](https://blinktrade.com/docs/#my-orders), so you can get all your filled, open and cancelled orders as follows.

```js
  return blinktrade.myOrders({
    filter: ['has_leaves_qty eq 1'] // Open Orders
    filter: ['has_cum_qty eq 1'] // Filled Orders
    filter: ['has_cxl_qty eq 1'] // Cancelled Orders
  })
```

And [requestLedger](https://blinktrade.com/docs/#ledger) is where you can get all operations done in your account, including trading fees, take a look at the ledger table to understand how the ledger is structured, and the operation of each line means.

**Comment by felipegtx** [comment]
@cesardeazevedo sorry but that table doesn't make much sense to me. 

Can you tell me which one is the field that relates to the trading fee inside the `LedgerListGrp` collection?

**Comment by cesardeazevedo** [comment]
It's indeed a bit confusing, the `Description: "TF"` stands for Trade Fee, which is what you looking for, you can find all the descriptions in this switch (https://github.com/blinktrade/frontend/blob/f93ed590d2cafcab032fd67bc1ffd49f2d02ef30/jsdev/bitex/ui/ledger_activity.js#L164-L194), will add them to the documentation.

**Comment by felipegtx** [comment]
So, just to make sure I got it. The ledger will give me different items in the `LedgerListGrp` for the order and the trading fees, right? What are those other types of Fees in the ledger description list?

**Comment by felipegtx** [comment]
@cesardeazevedo when I execute the following call, even though I passed `pageSize: 200` it only returns me the last `100`.

```
 blinktradeWs.requestLedger( { pageSize: 200 })
```

What's the best way to overcome this?

**Comment by cesardeazevedo** [comment]
You can't fetch more than 100 rows, you need to paginate if want more data.

**Comment by arvanus** [comment]
Hi.
I think this feature stopped again, I`m using direct access to websockets,  filtering just open orders but is returning everything!
Call:
    {
    "MsgType": "U4",    
    "OrdersReqID": 1,
    "Page": 0,           
     "has_leaves_qty": 1,
    "PageSize": 20
	}
And it returns everything, every closed order (20 orders)
(I`m using Foxbit)

**Comment by cesardeazevedo** [comment]
@arvanus The raw message is actually `{ "MsgType": "U4", "Filter": ['has_leaves_qty eq 1'] }`

**Comment by arvanus** [comment]
It worked, Thanks!
Strangely it was working, but it's ok, Thanks again!
