### ISSUE TITLE
REST Api returning Wrong Value

### ISSUE THREAD

**Issue by pedrosoares** [blinktrade/BlinkTradeJS#31]
I'm using the REST Api with C++ application that I`m developing, but the rest API is returning the wrong value. 
For example, if I request this url "https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC" I receive this response: 
{"high": 64800.0, "vol": 1626.534244, "buy": 54800.11, "last": 54800.1, "low": 49000.0, "pair": "BTCBRL", "sell": 54849.99, "vol_brl": 95239499.81959416}. 
But, if I enter on foxbit website, the cotation is between 49999 and 50000. 
The same happens with the order book.
What is wrong?

**Comment by cesardeazevedo** [comment]
Hi @pedrosoares, 

Thanks for report, we're completely aware of it, and we are trying to fix it as soon as possible, the only thing that i could recommend you right now is just wait until we can normalize it, we really apologize for that situation.

**Comment by pedrosoares** [comment]
Thanks @cesardeazevedo,
There any workaround to do while I wait this bug to be fixed? I have a bot that sells my bitcoin when the price goes down to much, and is very importante that they keep running.
Thanks again.

**Comment by LeoFCardoso** [comment]
Try to consume web socket API and compare order books prices with last trade info (that one has timestamp). So you can check if your read values looks correct.

**Comment by pedrosoares** [comment]
Now is working like a charm.
