### ISSUE TITLE
[Question] Error Too many messages per second

### ISSUE THREAD

**Issue by alissonrodrigz** [blinktrade/BlinkTradeJS#34]
I've been receiving the following error a lot:
Error: 16 messages in the last second Too many messages per second

Could you please explain a bit more of this issue? Is my application sending more than 16 messages per second (which is not happening based on my tests) or the server is trying to send me all this messages?
How can I avoid this issue?

**Comment by cesardeazevedo** [comment]
This means that you are sending 16 messages per second, not receiving it.
i don't know what's going on there, but if you are calling any function inside a loop will definitely causes this exception.

If you could explain me a little bit more about which function you are using and when, i might be able to help you.

**Comment by alissonrodrigz** [comment]
I am still trying to figure out where the issue is. I am using the code from https://github.com/eduardofx/Foxbit_Bot . Sometimes it fails on Buy mode, sometimes on Sell.
There is a function (index.js->VerifyChanges) that checks if a new order should be placed (cancelling the previous one). This function is called basically every time that blinkTrade sends a message, so I doubt that blinktrade sends more than 8 messages, which would cause other 16 responses (1 cancel + 1 sendOrder) on a second.

**Comment by cesardeazevedo** [comment]
The function `VerifyChanges` is called on each market data event, basically every change on the orderbook, which can be a lot if there's a lot a bots sending and cancelling orders, you just need to getting in deep on the if's conditions and try to understand if all the checks are correct and not sending multiple sendOrder / cancelOrder messages.

Due the code complexity, i can't get further than that for now.

**Comment by alissonrodrigz** [comment]
Thanks man, you already helped a lot.
