### ISSUE TITLE
subscribeToOrderbook returning undefined values (WebSocket API)

### ISSUE THREAD

**Issue by Judahh** [blinktrade/BlinkTradeJS#36]
I receive callbacks from the subscription, but It returns orders with undefined values, so it's impossible to update my orderbook.

Examples:
delete Order: { index: 3,
  price: NaN,
  size: NaN,
  side: 'sell',
  userId: undefined,
  orderId: undefined,
  symbol: 'BTCBRL',
  time: 'Invalid Date',
  type: 'OB:DELETE_ORDER' }

delete order thru: { index: 1,
  price: NaN,
  size: NaN,
  side: 'buy',
  userId: undefined,
  orderId: undefined,
  symbol: 'BTCBRL',
  time: 'Invalid Date',
  type: 'OB:DELETE_ORDERS_THRU' }

**Comment by Judahh** [comment]
Will the index value be outdated as new values are updated, deleted and added? Or should I update or remove the index value?

**Comment by cesardeazevedo** [comment]
I am not sure if i understood your question, but once you received a deleted event, you just remove the order from the list based on the received index, and once you removed, you won't use this value again, future events will just happen naturally in realtime, not outdated.

**Comment by Judahh** [comment]
Ok, so the index used is the index of the updated list of orders. But when I receive a new trade it has an undefined index, so I have to look for an order using the trade's order ID. If the order is completely filled I will receive a delete event with the index or should I delete it when is filled and the server will do the same? Because If I do something that differs from the server implementation my list of orders will be outdated and new events will delete and update wrong orders.

**Comment by cesardeazevedo** [comment]
There's no index for new trades, the index is just used on the orderbook, so you can put the order on the right position, the index doesn't make sense for new trades.

You don't have to listen to new trades (`OB:TRADE_NEW`) in order to delete an order from the book, when a new trade occurs you will receive both `OB:TRADE_NEW` and `OB:DELETE_ORDER` (or `OB:DELETE_ORDERS_THRU` in case of multiple executions) events
