### ISSUE TITLE
Balance requests always return SyntaxError in JSON

### ISSUE THREAD

**Issue by Galeba** [blinktrade/BlinkTradeJS#38]
When I run the code below to request the balance,
`blinktrade.balance({
    MsgType: "U2",
    BalanceReqID: 1
}).then(function(balance) { 
  console.log(balance);
});`

I always receive the following error message:
`SyntaxError: Unexpected token ? in JSON at position 0`

Also, the request only does NOT return the error below after a few tries (normally 'works' on second try):
``> Error: Error: U2 Not authorized
    at BlinkTradeWS.onMessage (C:\Users\.....\blinktrade\lib\wsTransport.js:164:15)
    at WebSocket.onMessage (C:\Users\.....\ws\lib\EventTarget.js:99:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (C:\Users\.....\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\.....\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\Users\.....\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\Users\.....\ws\lib\Receiver.js:165:16
)
    at Receiver.add (C:\Users\.....\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (C:\Users\.....\ws\lib\WebSocket.js:138:22)``

But that isn't the trouble. Even when I get past it, I can't find a way to read (balance). 
Is there a way I can remove the "?" ? Some method? Something I'm missing?
By the way, I'm running the code on Node.js. Could it have something to do with it? 
I don't think so, but who knows?
I don't recall doing anything different than the examples given in the docs.
Every other kind of request or operation I did worked. The account at hand has zero balance and is in the testnet.

Thanks.
Sorry people. I found a way to make balance work. I still don't understand very well how everything happened, but all is fine now.

**Comment by cesardeazevedo** [comment]
Hi, glad that you found a solution, not sure how you was doing before, but you need to connect on the websocket first before send any message, and login to your account to read your balances.

This is a minimum implementation.

```js
const { BlinkTradeWS } = require('blinktrade')

const blinktrade = new BlinkTradeWS({
  brokerId: 4,
  prod: false,
})

blinktrade.connect().then(() => {
  console.log('WebSocket Connected');
  return blinktrade.login({
    username: 'API_KEY',
    password: 'API_PASSWORD',
  })
}).then(() => {
  return blinktrade.balance()
}).then((balance) => {
  console.log(balance)
})
```

Also, you don't have to touch at any `MsgType` or `BalanceReqID`, the blinktradejs already abstract this for you, the [docs](https://blinktrade.com/docs) just show how the message is sent to our backend.
