### ISSUE TITLE
MSG_LOGIN_ERROR_INVALID_USERNAME_OR_PASSWORD

### ISSUE THREAD

**Issue by arvanus** [blinktrade/BlinkTradeJS#46]
Erro meu, favor ignorar este chamado

**Comment by arvanus** [comment]
Note: first 2 attempts return this:

{"Username": "", "NeedSecondFactor": false, "UserStatusText": "MSG_BUSY_REJECTION", "SecondFactorType": null, "UserStatus": 3, "UserReqID": 1530032222, "MsgType": "BF"}

**Comment by arvanus** [comment]
Achei o problema, troquei uma variável

**Comment by cesardeazevedo** [comment]
I was about to answer you, glad that you solved, but yeah, your API Key will be automatically revoked after 3 login failures attempts.

**Comment by arvanus** [comment]
Thanks, and good to know about 3 login failure attempts.


*Ps: this afternoon ticker was returning some null values in BestAsk and BestBid.

{"SellVolume": 9687668083, "LowPx": 2481051000000, "LastPx": 2559690000000, "MsgType": "f", "BestAsk": null, "HighPx": 2559698000000, "BuyVolume": 243733383041975, "BestBid": null, "Symbol": "BTCBRL", "SecurityStatusReqID": 1234, "Market": "BLINK"}

But now it`s working fine
