### ISSUE TITLE
Invalid broker

### ISSUE THREAD

**Issue by khaleb85** [blinktrade/BlinkTradeJS#52]
I'm trying to connect via websocket to see data from froxbit (BROKER ID = 4) but I'm facing an error:  
![image](https://user-images.githubusercontent.com/15098143/42353151-28284fec-8095-11e8-93d5-0205d55275d3.png)

What happened? I looked at blinktrade docs and I saw the Foxbit name with a scratched...
![image](https://user-images.githubusercontent.com/15098143/42353216-82d47c86-8095-11e8-8a40-85c6a2ae9362.png)

Did something happen with foxbit api? thanks for your help

**Comment by pinhopro** [comment]
Foxbit is not part of blinktrade network anymore. In case you wish to trade in Brazil using Blinktrade's api, you should create an account with bitcambio.com.br, which is now the brazil branch of blinktrade
