### ISSUE TITLE
Know if a trade has been done as taker

### ISSUE THREAD

**Issue by machard** [blinktrade/BlinkTradeJS#56]
Hi,

Is the AggressorIndicator flag present in the report when a fill happen ?
If not how can I know if the trade was done as a taker or a maker ?

Thx

**Comment by pinhopro** [comment]
When you receive an Execution Report ( MsgType = '8' ), you will receive the field "Side", which indicates the side where execution took place.

If you send a buy order ( side=1) and the execution was on the sell side (side=2), then your order was an agressor order, and vice-versa

Thanks,
Rodrigo

**Comment by machard** [comment]
thx

**Comment by machard** [comment]
@pinhopro 
Just to be sure.
If i post a buy order with Side : 1, when a trade happen the side field of the execution report can be either 1 or 2 ? 1 meaning my order was executed as a maker and 2 it was executed as a taker

**Comment by machard** [comment]
I see ExecSide. I think Side will always be the side of the order and ExecSide is the field i need to check agains Side, right ?

Maker => ExecSide = Side
Taker => ExecSide != Side

**Comment by machard** [comment]
well i got trades executed so i was wrong the good answer is:

Maker => ExecSide != Side
Taker => ExecSide == Side
