### ISSUE TITLE
tickerWebSocket.js dont works

### ISSUE THREAD

**Issue by flavioscunha95** [blinktrade/BlinkTradeJS#58]
I paste the code in a .js file:

![image](https://user-images.githubusercontent.com/42319159/44003070-094019ec-9e23-11e8-8910-3f1e0f8ae3f1.png)

... but occurs the error:
![image](https://user-images.githubusercontent.com/42319159/44003021-4669389a-9e22-11e8-9583-023fefa33fd4.png)

Help me, please

**Comment by cesardeazevedo** [comment]
The example is working fine here
![screen shot 2018-08-12 at 11 32 00](https://user-images.githubusercontent.com/5366959/44003092-5ed69c00-9e23-11e8-9e22-f0c01df27a68.png)

How exactly you are trying to running it?

**Comment by flavioscunha95** [comment]
Hello Cesar!
I am running in Node.js command prompt... I run the commands first 'npm install request' and 'npm install blinktrad', then run my file named 'requesttest.js', but occurs that error...
Some idea what happen?

**Comment by flavioscunha95** [comment]
I use bitcambio.com, brokerId=11

**Comment by cesardeazevedo** [comment]
which node.js version are you using?

**Comment by flavioscunha95** [comment]
The most recent, 10.8.0

**Comment by flavioscunha95** [comment]
I have a lot of trouble with JS, is there any possibility of implementing this same routine in Visual Basic?

**Comment by flavioscunha95** [comment]
How do you run?

**Comment by cesardeazevedo** [comment]
I just simply run with `node file.js` on the terminal.

I don't use windows, so i don't know how to help you.

**Comment by flavioscunha95** [comment]
Thanks! I was typing only 'filename.js' and not 'node filename.js'… lol
Resolved

**Comment by cesardeazevedo** [comment]
Glad that you solved it
