### ISSUE TITLE
`onWithdrawRefresh()` doesn't work

### ISSUE THREAD

**Issue by amingilani** [blinktrade/BlinkTradeJS#6]
The code that watches state change of withdrawals never executes, but the watcher for the specific withdrawals does.

```
// this doesn't ever execute
blinktrade.onWithdrawRefresh(function(withdraw) {
  console.log(withdraw);
});

// this works for `new` and `cancelled` withdrawals
blinktrade.requestWithdraw({
    "amount": parseInt(1200 * 1e8),
    "currency": "PKR",
    "method": "BankIslami",
    "data": {
        "AccountName": "A Girl Is No One",
        "AccountNumber": "123477",
    }
}).on('WITHDRAW_REFRESH', function(withdraw) {
    console.log(withdraw);
});
```

**Comment by cesardeazevedo** [comment]
I'm investigating.

**Comment by amingilani** [comment]
@cesardeazevedo in the meantime, is there a temp workaround for this? :) this functionality is kinda crucial to my app :)

**Comment by cesardeazevedo** [comment]
Yes, sure, will take a look at it right now, just give me 10 minutes.

**Comment by cesardeazevedo** [comment]
A question, have you logged with `blinktrade.login()`?, i think my examples was missing that...

**Comment by amingilani** [comment]
@cesardeazevedo yes I did! I can create withdrawals programmatically and they show up on my account as well. I then cancel them from my account.

This totally works:
```
.on('WITHDRAW_REFRESH', function(withdraw) {
    console.log(withdraw);
});
```

But I need a catch all that notifies my app of every single `withdrawal` state change, which is exactly what `onWithdrawRefresh` does.

**Comment by amingilani** [comment]
[This](https://github.com/payloadtech/payload-urdubit/blob/master/app.js#L55-L64) is my code, which does create a withdrawal.

**Comment by cesardeazevedo** [comment]
Ok, i got it, there's something wrong when using `onWithdrawRefresh` together with `requestWithdraw`, it seems that is some listener is overwriting the `onWithdrawRefresh` listener, and removing `requestWithdraw` the `onWithdrawRefresh` works as expected, can you try removing `requestWithdraw` and just leave `onWithdrawRefresh` for tests? I'm gonna fix that, sorry.

**Comment by amingilani** [comment]
Not at all, thank you! I'm testing this out right now! Super excited about integrating with Urdubit. It's the only bitcoin exchange in my country.

**Comment by amingilani** [comment]
@cesardeazevedo it appears that you were right. Running the following alone notifies me of state changes to the withdrawals.

```javascript
        console.log('Listening for withdrawals');
        blinktrade.onWithdrawRefresh(function(withdraw) {
            console.log(withdraw);
        });
```

Is there an ETA on when you could push a fix for this? This is kinda critical :)

**Comment by cesardeazevedo** [comment]
Yes indeed, I'm plan to publish a new release tomorrow with the latest fixes...
