### ISSUE TITLE
Add documentation on rate limit

### ISSUE THREAD

**Issue by amingilani** [blinktrade/BlinkTradeJS#8]
I just hit `Error: 16 messages in the last second Too many messages per second` this should totally be included in the documentation ;)

**Comment by cesardeazevedo** [comment]
Yes indeed, i'll add this on the docs soon, you could also report it on [docs repository](https://github.com/blinktrade/docs)

**Comment by amingilani** [comment]
I didn't know that existed! Cross posting there.
