### ISSUE TITLE
How do I fetch order by OrderId?

### ISSUE THREAD

**Issue by amingilani** [blinktrade/BlinkTradeJS#9]
Hello, I've noticed that the execution report doesn't seem to show the settlement price, e.g.:

```javascript
{ OrderID: 1459146238526, 
  ExecID: 566318, 
  ExecType: '2', 
  OrdStatus: '2', 
  CumQty: 1254716, 
  Symbol: 'BTCPKR', 
  OrderQty: 1254716, 
  LastShares: 1254716, 
  LastPx: 7851100000000, 
  Price: 100000000, 
  TimeInForce: '1', 
  LeavesQty: 0, 
  MsgType: '8', 
  ExecSide: '2', 
  OrdType: '2', 
  CxlQty: 0, 
  Side: '2', 
  ClOrdID: 4743461, 
  AvgPx: 7851100000000 } 
```

Is there anyway for me to lookup a specific order status by `OrderID`? The current [`myOrders`](https://github.com/blinktrade/BlinkTradeJS#myorders-websocket-rest) method returns a list of orders, and it's paginated by 40 orders each. I can't use that since if over 40 of my orders are executed near simultaneously, the list will not contain them.

**Comment by amingilani** [comment]
It appears as though the execution price is `LastPx * OrderQty / 1e16`. @cesardeazevedo can you confirm if this will always hold true?

**Comment by cesardeazevedo** [comment]
`LastPx` means the current price of the execution fill, but once you can receive multiples execution reports, you might take a look at the `AvgPx`, which is the average price of all fills of the order, and the value shown on the "Orders history" page, which fetchs `myOrders`.

There's no way to lookup a specific `OrderID`, and `myOrders` will only lists the latest orders and doesn't lists executions, just the final state of your orders, if your order gets 40 executions, it doesn't really matter, it will just list your order once, together with the average price `AvgPx`, so i think you can get your order right on the top.

Tell me if you got it.

**Comment by amingilani** [comment]
I understand, but in my case, I meant that if my application makes over 40 orders in quick succession (very possible) I wouldn't be able to find the order in `myOrders` by the time the callback executes.

Regardless, so to get the final Fiat value of an order I should use `(AvgPx * OrderQty / 1e16)toFixed(0)`, correct?

**Comment by cesardeazevedo** [comment]
Yes, your formula to get the fiat value is correct, but If you are going to get the value with`myOrders` you would just use `Volume` property.

**Comment by amingilani** [comment]
Actually, would it make more sense to use `CumQty`?

I'm assuming `CumQty` and `AvgPx` are the quantity and price for the entire order while `Qty` and `LastPx` are only for the latest partial?

**Comment by cesardeazevedo** [comment]
Oh yes, my bad, you should use `CumQty` instead, since you are getting multiples executions reports, i was just confusing on how you are getting those values.

You can also check the `fix` protocol to get more details about each field, is not all properties that we've implemented, but most of properties you can find there, except some functions that has been overwritten by the client.

http://www.onixs.biz/fix-dictionary/4.0/msgType_8_8.html

**Comment by amingilani** [comment]
Thank you! This answers all my questions

**Comment by amingilani** [comment]
Not to prolong a discussion, but maybe add an `ExecutionPrice` method to the SDK that does these calculation? I'm sure a lot of people may be similarly confused in the future!
